package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"gin-quick-start/internal/graphql/model"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return &model.Health{
		Available: true,
		Name:      r.Config.App.Name,
		Version:   r.Config.App.Version,
		Env:       r.Config.App.Env,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.AccountDetail, error) {
	account, err := currentAccount(ctx)
	if err != nil {
		return nil, err
	}

	// 只查令牌对应的账号自己的默认组织，不接受任何入参指定账号 ID
	org, err := r.Accounts.DefaultOrg(ctx, account.ID)
	if err != nil {
		return nil, err
	}

	return &model.AccountDetail{
		Account: convertAccount(account),
		Org:     convertOrg(org),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
